### ISSUE TITLE
Još jedan tvoj propali projekat

### ISSUE THREAD

**Issue by R00tS3c** [RisteDimitrievski/portal#1]
Zašto ti je svaki projekat propo ko i onaj gt.vip HAHAAHAAHHAHAHAHAAHHAAHHAH

**Comment by RisteDimitrievski** [comment]
Tesko je to razumeti na tvojim godinama, a vidi se po slici o kakvoj osobi se radi, tako da cu samo da zakljucam status.  Nisi vredan za diskusiju Nikita.

#lockic.
